import type { Metadata } from "next";
import "./globals.css";
import { manrope } from "@/utils/font";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "./auth-provider";
import { Providers } from "./provider";

export const metadata: Metadata = {
  title: "Cosmetic Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${manrope.className} antialiased`}>
        <Providers>
          <AuthProvider>{children}</AuthProvider>
        </Providers>

        <ToastContainer
          autoClose={2000}
          className={"text-sm font-medium"}
          position="top-right"
        />
      </body>
    </html>
  );
}
